name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Push to Hugging Face
        run: |
          git clone https://huggingface.co/spaces/abhik-01/trip-planner hf-space
          rsync -av --exclude='.git' ./ hf-space/
          cd hf-space
          git add .
          git commit -m "Deploy from GitHub" || echo "No changes to commit"
          git push https://user:$HF_TOKEN@huggingface.co/spaces/abhik-01/trip-planner main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
